/*
 * Подборка для Mini App: настоящая афиша Пушкинской карты.
 *
 * Собрана из раздела Пушкинской карты билетного оператора — того же
 * источника, который разбирает TicketlandParser на бэкенде: читаются блоки
 * schema.org/Event в JSON-LD, а не вёрстка. Форма объекта повторяет проекцию
 * FeedCardRow, поэтому при переходе на REST разметка не изменится.
 *
 * Почему снимок, а не запрос на лету: Mini App обязан работать без внешней
 * сети, и в нём пока нет своего бэкенда. Снимок сделан 2026-09-29; чтобы
 * обновить, повторите импорт и перегенерируйте этот файл.
 *
 * ticketUrl ведёт на страницу самого мероприятия у оператора — покупка
 * доводится до конца, и подтверждение покупки в Mini App проверяется
 * по-настоящему. Афиши скачаны в assets/events/, источники — в CREDITS.md.
 *
 * Координаты площадок: геокодер Nominatim, а для тех, кого он не знает, —
 * адреса из R__seed_venues_import.sql. distanceKm считается от центра Москвы:
 * своего адреса у Mini App пока нет, он появится вместе с онбордингом.
 *
 * Чего здесь нет: кино. В разделе Пушкинской карты у этого оператора его нет
 * вовсе, поэтому кошелёк «Кино» в профиле останется нетронутым — это свойство
 * источника, а не ошибка.
 */
const MOCK_EVENTS = [
  {
    sessionId: 1001,
    eventId: 201,
    title: 'Виртуальная инсталляция «Внутри шедевра»',
    summary: 'Центр современного искусства «Марс», Пушкарёв пер., 5. В афише один сеанс.',
    category: 'MUSEUM',
    photo: 'assets/events/virtualnaya-installyaciya-vnutri-shede-01.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/0e/ce/0eceec4226a98b8abbc35ece2dbbf5ad.jpg',
    eventUrl: 'https://www.ticketland.ru/drugoe/centr-sovremennogo-iskusstva-mars/virtualnaya-installyaciya-vnutri-shedevra/',
    ticketUrl: 'https://www.ticketland.ru/drugoe/centr-sovremennogo-iskusstva-mars/virtualnaya-installyaciya-vnutri-shedevra/',
    venueName: 'Центр современного искусства «Марс»',
    venueAddress: 'Пушкарёв пер., 5',
    startsAt: '2026-09-29T12:00:00+03:00',
    priceRub: 1200,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1002,
    eventId: 202,
    title: 'Ни в какие рамки',
    summary: 'Центр современного искусства «Марс», Пушкарёв пер., 5. В афише один сеанс.',
    category: 'MUSEUM',
    photo: 'assets/events/ni-v-kakie-ramki-02.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/1f/58/1f5820ec10eb942c9e84d8735556f8cc.png',
    eventUrl: 'https://www.ticketland.ru/drugoe/centr-sovremennogo-iskusstva-mars/vistavka-ni-v-kakie-ramki/',
    ticketUrl: 'https://www.ticketland.ru/drugoe/centr-sovremennogo-iskusstva-mars/vistavka-ni-v-kakie-ramki/',
    venueName: 'Центр современного искусства «Марс»',
    venueAddress: 'Пушкарёв пер., 5',
    startsAt: '2026-09-29T12:00:00+03:00',
    priceRub: 1200,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1003,
    eventId: 203,
    title: 'Сон в музее',
    summary: 'Центр современного искусства «Марс», Пушкарёв пер., 5. В афише один сеанс.',
    category: 'MUSEUM',
    photo: 'assets/events/son-v-muzee-03.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/66/e3/66e36c86c3ca53dd35020fc981282d00_6703862.jpg',
    eventUrl: 'https://www.ticketland.ru/drugoe/centr-sovremennogo-iskusstva-mars/son-v-muzee/',
    ticketUrl: 'https://www.ticketland.ru/drugoe/centr-sovremennogo-iskusstva-mars/son-v-muzee/',
    venueName: 'Центр современного искусства «Марс»',
    venueAddress: 'Пушкарёв пер., 5',
    startsAt: '2026-09-29T12:00:00+03:00',
    priceRub: 1400,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1004,
    eventId: 204,
    title: 'Р. Леонкавалло. Паяцы',
    summary: 'Классика, оперетты. Центр оперного пения Галины Вишневской, ул. Остоженка, 25с1. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/r-leonkavallo-payacy-04.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/53/7a/537ac59b6a2a549a7496866b0c6b3ea9.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/centr-opernogo-peniya-galiny-vishnevskoy/r-leonkavallo-payacy/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/centr-opernogo-peniya-galiny-vishnevskoy/r-leonkavallo-payacy/',
    venueName: 'Центр оперного пения Галины Вишневской',
    venueAddress: 'ул. Остоженка, 25с1',
    startsAt: '2026-09-29T19:00:00+03:00',
    priceRub: 200,
    distanceKm: 2.3,
    sessionCount: 1
  },
  {
    sessionId: 1005,
    eventId: 205,
    title: 'Сашашишин',
    summary: 'Драмы. Театр «Современник», Чистопрудный б-р, 19А. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/sashashishin-05.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/d2/83/d283f0f99ba116b7c96e1194a348d25e.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/moskovskiy-teatr-sovremennik/sashashishin/',
    ticketUrl: 'https://www.ticketland.ru/teatry/moskovskiy-teatr-sovremennik/sashashishin/',
    venueName: 'Театр «Современник»',
    venueAddress: 'Чистопрудный б-р, 19А',
    startsAt: '2026-09-29T19:00:00+03:00',
    priceRub: 2500,
    distanceKm: 1.7,
    sessionCount: 1
  },
  {
    sessionId: 1006,
    eventId: 206,
    title: 'Чайковский и Рахманинов: два голоса русской души',
    summary: 'Концерты, инструментальная музыка. Музыкальная квартира на Тверской, ул. Тверская, 12с7. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/chaikovskii-i-rahmaninov-dva-golosa-ru-06.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/79/7a/797a5191ba87a2356e3322a07c22fc6f.png',
    eventUrl: 'https://www.ticketland.ru/teatry/muzykalnaya-kvartira-na-tverskoy/chaykovskiy-i-rakhmaninov-dva-golosa-russkoy-dushi/',
    ticketUrl: 'https://www.ticketland.ru/teatry/muzykalnaya-kvartira-na-tverskoy/chaykovskiy-i-rakhmaninov-dva-golosa-russkoy-dushi/',
    venueName: 'Музыкальная квартира на Тверской',
    venueAddress: 'ул. Тверская, 12с7',
    startsAt: '2026-09-29T19:00:00+03:00',
    priceRub: 600,
    distanceKm: 1.5,
    sessionCount: 1
  },
  {
    sessionId: 1007,
    eventId: 207,
    title: 'Дом под снос',
    summary: 'Комедии. Центральный академический театр Российской Армии, Суворовская пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/dom-pod-snos-07.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/show/4195879/1.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-rossiyskoy-armii/dom-pod-snos/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-rossiyskoy-armii/dom-pod-snos/',
    venueName: 'Центральный академический театр Российской Армии',
    venueAddress: 'Суворовская пл., 2',
    startsAt: '2026-09-30T19:00:00+03:00',
    priceRub: 2000,
    distanceKm: 3.5,
    sessionCount: 1
  },
  {
    sessionId: 1008,
    eventId: 208,
    title: 'Народная артистка России Надежда Крыгина. «Вера, Надежда, Любовь»',
    summary: 'Поп-музыка. Москонцерт Холл, Каланчёвская ул., 33с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/narodnaya-artistka-rossii-nadezhda-kry-08.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/d3/a9/d3a9f624f67e383261a8734bb0b1ed1f.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/narodnaya-artistka-rossii-nadezhda-krygina-vera-nadezhda-lyubov/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/narodnaya-artistka-rossii-nadezhda-krygina-vera-nadezhda-lyubov/',
    venueName: 'Москонцерт Холл',
    venueAddress: 'Каланчёвская ул., 33с1',
    startsAt: '2026-09-30T19:00:00+03:00',
    priceRub: 400,
    distanceKm: 3,
    sessionCount: 1
  },
  {
    sessionId: 1009,
    eventId: 209,
    title: 'Верни мне музыку. Песни Арно Бабаджаняна',
    summary: 'Народная музыка, романсы. Музыкальная квартира на Тверской, ул. Тверская, 12с7. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/verni-mne-muzyku-pesni-arno-babadzhany-09.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/bc/ad/bcad5adddededdfc1b8c4752d536774e.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/muzykalnaya-kvartira-na-tverskoy/verni-mne-muzyku-pesni-arno-babadzhanyana/',
    ticketUrl: 'https://www.ticketland.ru/teatry/muzykalnaya-kvartira-na-tverskoy/verni-mne-muzyku-pesni-arno-babadzhanyana/',
    venueName: 'Музыкальная квартира на Тверской',
    venueAddress: 'ул. Тверская, 12с7',
    startsAt: '2026-09-30T19:00:00+03:00',
    priceRub: 700,
    distanceKm: 1.5,
    sessionCount: 1
  },
  {
    sessionId: 1010,
    eventId: 210,
    title: 'Похищение Европы',
    summary: 'Опера. Театр имени Сац, пр-т Вернадского, 5. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/pohischenie-evropy-10.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/81/9d/819d2adb4cb5033c50d9351d8e5007a1.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/pokhischenie-evropy/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/pokhischenie-evropy/',
    venueName: 'Театр имени Сац',
    venueAddress: 'пр-т Вернадского, 5',
    startsAt: '2026-10-01T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 8.3,
    sessionCount: 1
  },
  {
    sessionId: 1011,
    eventId: 211,
    title: 'Шестеро любимых',
    summary: 'Комедии. Театр на Таганке (Сцена на Факельном), Факельный пер., 3. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/shestero-lyubimyh-11.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/c9/f7/c9f70034a977e591c10ed664ce176967_4818729.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke-scena-na-fakelnom/shestero-lyubimykh/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke-scena-na-fakelnom/shestero-lyubimykh/',
    venueName: 'Театр на Таганке (Сцена на Факельном)',
    venueAddress: 'Факельный пер., 3',
    startsAt: '2026-10-01T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 3,
    sessionCount: 1
  },
  {
    sessionId: 1012,
    eventId: 212,
    title: 'Кармен',
    summary: 'Опера. Музыкальный театр имени Станиславского и Немировича-Данченко, ул. Большая Дмитровка, 17. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/karmen-12.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/f6/14/f6149517f48079af5d6c0e94ef9879f1_1855099.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/muzykalnyy-teatr-im-stanislavskogo-i-nemirovicha-danchenko/karmen-mamt/',
    ticketUrl: 'https://www.ticketland.ru/teatry/muzykalnyy-teatr-im-stanislavskogo-i-nemirovicha-danchenko/karmen-mamt/',
    venueName: 'Музыкальный театр имени Станиславского и Немировича-Данченко',
    venueAddress: 'ул. Большая Дмитровка, 17',
    startsAt: '2026-10-01T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 1.3,
    sessionCount: 1
  },
  {
    sessionId: 1013,
    eventId: 213,
    title: 'Девять',
    summary: 'Драмы. Театр Гоголя, ул. Казакова, 8. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/devyat-13.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/0b/cf/0bcf3eae78e11895020f470b94a37b7e.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-im-nvgogolya/devyat-spektakl/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-im-nvgogolya/devyat-spektakl/',
    venueName: 'Театр Гоголя',
    venueAddress: 'ул. Казакова, 8',
    startsAt: '2026-10-01T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 2.9,
    sessionCount: 1
  },
  {
    sessionId: 1014,
    eventId: 214,
    title: 'DSCH 120 Б. Андрианов, П. Милюков, МГСО, дирижёр - И. Рудин',
    summary: 'Концерты, инструментальная музыка. МКЗ «Зарядье», ул. Варварка, 6с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/dsch-120-b-andrianov-p-milyukov-mgso-d-14.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/db/3d/db3d3bbcfe3c66a68ba6bd17a017257c.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/dsch-120-b-andrianov-p-milyukov-mgso-dirizhyor-i-rudin/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/dsch-120-b-andrianov-p-milyukov-mgso-dirizhyor-i-rudin/',
    venueName: 'МКЗ «Зарядье»',
    venueAddress: 'ул. Варварка, 6с1',
    startsAt: '2026-10-01T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 0.6,
    sessionCount: 1
  },
  {
    sessionId: 1015,
    eventId: 215,
    title: 'Шерлок Холмс',
    summary: 'Детям, балет. Театр имени Сац, пр-т Вернадского, 5. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/sherlok-holms-15.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/54/7b/547b1a042b535ca5973aa4bb09f838ea_1856235.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/sherlok-kholms/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/sherlok-kholms/',
    venueName: 'Театр имени Сац',
    venueAddress: 'пр-т Вернадского, 5',
    startsAt: '2026-10-02T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 8.3,
    sessionCount: 1
  },
  {
    sessionId: 1016,
    eventId: 216,
    title: '451 по Фаренгейту',
    summary: 'Драмы. Театр «Et Cetera» п/р Александра Калягина, Фролов пер., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/451-po-farengeitu-16.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/86/b3/86b39176e75f5ad9cddc98ebda41baf7.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-et-cetera-p-r-aleksandra-kalyagina/spektakl-451-po-farengeytu/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-et-cetera-p-r-aleksandra-kalyagina/spektakl-451-po-farengeytu/',
    venueName: 'Театр «Et Cetera» п/р Александра Калягина',
    venueAddress: 'Фролов пер., 2',
    startsAt: '2026-10-02T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 1.3,
    sessionCount: 1
  },
  {
    sessionId: 1017,
    eventId: 217,
    title: 'Онегин',
    summary: 'Театр на Таганке, ул. Земляной Вал, 76/21. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/onegin-17.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/88/76/88765e6c7ea36840048731d1afbfee9d.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/onegin-myuzikl/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/onegin-myuzikl/',
    venueName: 'Театр на Таганке',
    venueAddress: 'ул. Земляной Вал, 76/21',
    startsAt: '2026-10-02T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 2.4,
    sessionCount: 1
  },
  {
    sessionId: 1018,
    eventId: 218,
    title: 'Игнас Михильс',
    summary: 'Концерты, инструментальная музыка. МКЗ «Зарядье», ул. Варварка, 6с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/ignas-mihils-18.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/92/ae/92aed7e163f2e7809e669c5eaab71a93.jpeg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/ignas-mikhils-organ/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/ignas-mikhils-organ/',
    venueName: 'МКЗ «Зарядье»',
    venueAddress: 'ул. Варварка, 6с1',
    startsAt: '2026-10-02T19:00:00+03:00',
    priceRub: 500,
    distanceKm: 0.6,
    sessionCount: 1
  },
  {
    sessionId: 1019,
    eventId: 219,
    title: 'Сергей Старостин и проект «Этносфера»',
    summary: 'Концерты, инструментальная музыка. МКЗ «Зарядье», ул. Варварка, 6с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/sergei-starostin-i-proekt-etnosfera-19.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/67/d3/67d309a6d64fa51d779ad73c16791804.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/sergey-starostin-i-proekt-etnosfera/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/sergey-starostin-i-proekt-etnosfera/',
    venueName: 'МКЗ «Зарядье»',
    venueAddress: 'ул. Варварка, 6с1',
    startsAt: '2026-10-02T19:00:00+03:00',
    priceRub: 1300,
    distanceKm: 0.6,
    sessionCount: 1
  },
  {
    sessionId: 1020,
    eventId: 220,
    title: 'Кот в сапогах',
    summary: 'Детям от 7 до 11 лет. Театр имени Евгения Вахтангова, ул. Арбат, 26. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/kot-v-sapogah-20.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/12/21/122157cbe4752df8fe0ee0752724f987.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/kot-v-sapogakh/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/kot-v-sapogakh/',
    venueName: 'Театр имени Евгения Вахтангова',
    venueAddress: 'ул. Арбат, 26',
    startsAt: '2026-10-03T12:00:00+03:00',
    priceRub: 300,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1021,
    eventId: 221,
    title: 'Путешествие Незнайки',
    summary: 'Мюзиклы, детям от 7 до 11 лет. Театр имени Сац, пр-т Вернадского, 5. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/puteshestvie-neznaiki-21.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/aa/11/aa11df8283f8c7e7a89999fc66acf3e0_1855022.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/pyteshestvie-neznaiki/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/pyteshestvie-neznaiki/',
    venueName: 'Театр имени Сац',
    venueAddress: 'пр-т Вернадского, 5',
    startsAt: '2026-10-03T12:00:00+03:00',
    priceRub: 2000,
    distanceKm: 8.3,
    sessionCount: 1
  },
  {
    sessionId: 1022,
    eventId: 222,
    title: 'Экскурсия в квартиру Евгения Вахтангова',
    summary: 'Пешеходные экскурсии. Музей-квартира Вахтангова, Денежный пер., 12. В афише один сеанс.',
    category: 'EXCURSION',
    photo: 'assets/events/ekskursiya-v-kvartiru-evgeniya-vahtang-22.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/12/74/1274138b29f4db632e33aa106b9ede91.jpg',
    eventUrl: 'https://www.ticketland.ru/muzei/muzey-kvartira-vakhtangova/ekskursiya-v-kvartiru-evgeniya-vakhtangova/',
    ticketUrl: 'https://www.ticketland.ru/muzei/muzey-kvartira-vakhtangova/ekskursiya-v-kvartiru-evgeniya-vakhtangova/',
    venueName: 'Музей-квартира Вахтангова',
    venueAddress: 'Денежный пер., 12',
    startsAt: '2026-10-03T13:00:00+03:00',
    priceRub: 1200,
    distanceKm: 2.3,
    sessionCount: 1
  },
  {
    sessionId: 1023,
    eventId: 223,
    title: 'Есенин. Ты, Рассея моя, Рассея...',
    summary: 'Творческие вечера. Музыкальная квартира на Тверской, ул. Тверская, 12с7. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/esenin-ty-rasseya-moya-rasseya-23.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/31/d6/31d6d4b2f69daaf5c7d6dcfbd7406a08.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert/eseninty-rasseya-moya-rasseya/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert/eseninty-rasseya-moya-rasseya/',
    venueName: 'Музыкальная квартира на Тверской',
    venueAddress: 'ул. Тверская, 12с7',
    startsAt: '2026-10-03T17:00:00+03:00',
    priceRub: 600,
    distanceKm: 1.5,
    sessionCount: 1
  },
  {
    sessionId: 1024,
    eventId: 224,
    title: 'Лебединое озеро',
    summary: 'Балет. Москонцерт Холл, Каланчёвская ул., 33с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/lebedinoe-ozero-24.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/fd/4a/fd4a701c32442da5a46438569347996a.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/balet-lebedinoe-ozero-moskoncert/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/balet-lebedinoe-ozero-moskoncert/',
    venueName: 'Москонцерт Холл',
    venueAddress: 'Каланчёвская ул., 33с1',
    startsAt: '2026-10-03T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 3,
    sessionCount: 1
  },
  {
    sessionId: 1025,
    eventId: 225,
    title: 'Одноклассники',
    summary: 'Мелодрамы. Центральный академический театр Российской Армии, Суворовская пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/odnoklassniki-25.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/show/4195823/1.png',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-rossiyskoy-armii/spektakl-odnoklassniki/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-rossiyskoy-armii/spektakl-odnoklassniki/',
    venueName: 'Центральный академический театр Российской Армии',
    venueAddress: 'Суворовская пл., 2',
    startsAt: '2026-10-03T19:00:00+03:00',
    priceRub: 2000,
    distanceKm: 3.5,
    sessionCount: 1
  },
  {
    sessionId: 1026,
    eventId: 226,
    title: 'Навеки ваш - Сергей Есенин',
    summary: 'Драмы. МКЗ «Зарядье», ул. Варварка, 6с1. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/naveki-vash-sergei-esenin-26.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/bb/f7/bbf7b1f4c658721eea5e03e67f37abd5.jpeg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/naveki-vash-sergey-esenin/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/mkz-zaryade/naveki-vash-sergey-esenin/',
    venueName: 'МКЗ «Зарядье»',
    venueAddress: 'ул. Варварка, 6с1',
    startsAt: '2026-10-03T19:00:00+03:00',
    priceRub: 1800,
    distanceKm: 0.6,
    sessionCount: 1
  },
  {
    sessionId: 1027,
    eventId: 227,
    title: 'Леопольдштадт',
    summary: 'Драмы. РАМТ, Театральная пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/leopoldshtadt-27.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/6b/63/6b6315c7b63aa34e7efb53bf5d203b8d.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/ramt/leopoldshtadt/',
    ticketUrl: 'https://www.ticketland.ru/teatry/ramt/leopoldshtadt/',
    venueName: 'РАМТ',
    venueAddress: 'Театральная пл., 2',
    startsAt: '2026-10-03T19:00:00+03:00',
    priceRub: 800,
    distanceKm: 0.8,
    sessionCount: 1
  },
  {
    sessionId: 1028,
    eventId: 228,
    title: 'Муха-Цокотуха. Школьные годы',
    summary: 'Детям от 3 до 6 лет, детям от 7 до 11 лет. Театр имени Сац, пр-т Вернадского, 5. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/muha-cokotuha-shkolnye-gody-28.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/50/92/5092930b80a33d308eb2c2edab579dd0.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/mukha-cokotukha-shkolnye-gody/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-im-ni-sac/mukha-cokotukha-shkolnye-gody/',
    venueName: 'Театр имени Сац',
    venueAddress: 'пр-т Вернадского, 5',
    startsAt: '2026-10-04T13:00:00+03:00',
    priceRub: 1000,
    distanceKm: 8.3,
    sessionCount: 1
  },
  {
    sessionId: 1029,
    eventId: 229,
    title: 'Я хочу в школу',
    summary: 'Детям от 7 до 11 лет. РАМТ, Театральная пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/ya-hochu-v-shkolu-29.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/b1/59/b159c2dc272eb09276ad49be14314283.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/ramt/spektakl-ya-khochu-v-shkolu/',
    ticketUrl: 'https://www.ticketland.ru/teatry/ramt/spektakl-ya-khochu-v-shkolu/',
    venueName: 'РАМТ',
    venueAddress: 'Театральная пл., 2',
    startsAt: '2026-10-04T19:00:00+03:00',
    priceRub: 500,
    distanceKm: 0.8,
    sessionCount: 1
  },
  {
    sessionId: 1030,
    eventId: 230,
    title: 'Дон Жуан',
    summary: 'Классика, драмы. Музыкальный театр имени Станиславского и Немировича-Данченко, ул. Большая Дмитровка, 17. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/don-zhuan-30.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/show/2241532/1.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/muzykalnyy-teatr-im-stanislavskogo-i-nemirovicha-danchenko/don-zhuan/',
    ticketUrl: 'https://www.ticketland.ru/teatry/muzykalnyy-teatr-im-stanislavskogo-i-nemirovicha-danchenko/don-zhuan/',
    venueName: 'Музыкальный театр имени Станиславского и Немировича-Данченко',
    venueAddress: 'ул. Большая Дмитровка, 17',
    startsAt: '2026-10-04T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 1.3,
    sessionCount: 1
  },
  {
    sessionId: 1031,
    eventId: 231,
    title: 'Королева-мать',
    summary: 'Драмы. Новая сцена и Арт-кафе театра Вахтангова, ул. Арбат, 24. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/koroleva-mat-31.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/fe/66/fe66038979d28d52c4015cd2924e010b.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/koroleva-mat/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/koroleva-mat/',
    venueName: 'Новая сцена и Арт-кафе театра Вахтангова',
    venueAddress: 'ул. Арбат, 24',
    startsAt: '2026-10-04T19:30:00+03:00',
    priceRub: 1100,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1032,
    eventId: 232,
    title: 'Царь Эдип',
    summary: 'Драмы. Театр имени Евгения Вахтангова, ул. Арбат, 26. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/car-edip-32.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/a6/56/a656571b9c9d99b7cd9048b5775cb5d2.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/car-edip/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/car-edip/',
    venueName: 'Театр имени Евгения Вахтангова',
    venueAddress: 'ул. Арбат, 26',
    startsAt: '2026-10-05T19:00:00+03:00',
    priceRub: 1800,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1033,
    eventId: 233,
    title: 'Корова',
    summary: 'Драмы. Театр на Таганке (Сцена на Факельном), Факельный пер., 3. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/korova-33.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/de/7f/de7f1cbe2369632d5f0207ad085012c6.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke-scena-na-fakelnom/korova/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke-scena-na-fakelnom/korova/',
    venueName: 'Театр на Таганке (Сцена на Факельном)',
    venueAddress: 'Факельный пер., 3',
    startsAt: '2026-10-06T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 3,
    sessionCount: 1
  },
  {
    sessionId: 1034,
    eventId: 234,
    title: 'Свадьба Кречинского',
    summary: 'Комедии. Центральный академический театр Российской Армии, Суворовская пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/svadba-krechinskogo-34.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/8e/b9/8eb9280b49d1c41bad9832f9215f77c8.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-rossiyskoy-armii/svadba-krechinskogo/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-rossiyskoy-armii/svadba-krechinskogo/',
    venueName: 'Центральный академический театр Российской Армии',
    venueAddress: 'Суворовская пл., 2',
    startsAt: '2026-10-06T19:30:00+03:00',
    priceRub: 1000,
    distanceKm: 3.5,
    sessionCount: 1
  },
  {
    sessionId: 1035,
    eventId: 235,
    title: 'Маскарад',
    summary: 'Драмы. Театр на Таганке, ул. Земляной Вал, 76/21. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/maskarad-35.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/38/d2/38d2772d9ac9d82d279e430eb4874c45_6364545.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/maskarad/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/maskarad/',
    venueName: 'Театр на Таганке',
    venueAddress: 'ул. Земляной Вал, 76/21',
    startsAt: '2026-10-07T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 2.4,
    sessionCount: 1
  },
  {
    sessionId: 1036,
    eventId: 236,
    title: 'Театр',
    summary: 'Драмы. Театр имени Евгения Вахтангова, ул. Арбат, 26. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/teatr-36.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/e6/5b/e65bac763a34717bea545812e8792b4b.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/teatr/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/teatr/',
    venueName: 'Театр имени Евгения Вахтангова',
    venueAddress: 'ул. Арбат, 26',
    startsAt: '2026-10-08T19:00:00+03:00',
    priceRub: 700,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1037,
    eventId: 237,
    title: 'Алые паруса',
    summary: 'Детям, драмы. РАМТ, Театральная пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/alye-parusa-37.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/show/3943019/1.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/ramt/alye-parusa/',
    ticketUrl: 'https://www.ticketland.ru/teatry/ramt/alye-parusa/',
    venueName: 'РАМТ',
    venueAddress: 'Театральная пл., 2',
    startsAt: '2026-10-08T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 0.8,
    sessionCount: 1
  },
  {
    sessionId: 1038,
    eventId: 238,
    title: 'Гамлет',
    summary: 'Драмы. Театр на Таганке, ул. Земляной Вал, 76/21. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/gamlet-38.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/08/49/0849c61166b157dddbf642f12e2cabc2.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/gamlet-teatr-na-taganke/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/gamlet-teatr-na-taganke/',
    venueName: 'Театр на Таганке',
    venueAddress: 'ул. Земляной Вал, 76/21',
    startsAt: '2026-10-08T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 2.4,
    sessionCount: 1
  },
  {
    sessionId: 1039,
    eventId: 239,
    title: 'Мастер-класс',
    summary: 'Драмы. Новая сцена и Арт-кафе театра Вахтангова, ул. Арбат, 24. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/master-klass-39.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/26/b1/26b17d9033a5d1d39b0dade70255de01.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/novaya-scena-i-art-kafe-teatra-vakhtangova/master-klass/',
    ticketUrl: 'https://www.ticketland.ru/teatry/novaya-scena-i-art-kafe-teatra-vakhtangova/master-klass/',
    venueName: 'Новая сцена и Арт-кафе театра Вахтангова',
    venueAddress: 'ул. Арбат, 24',
    startsAt: '2026-10-08T19:30:00+03:00',
    priceRub: 1000,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1040,
    eventId: 240,
    title: 'Фауст',
    summary: 'Драмы. Театр имени Евгения Вахтангова, ул. Арбат, 26. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/faust-40.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/e4/02/e402030168e343c1a9e8d2996dc64c9a.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/faust/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/faust/',
    venueName: 'Театр имени Евгения Вахтангова',
    venueAddress: 'ул. Арбат, 26',
    startsAt: '2026-10-09T19:00:00+03:00',
    priceRub: 2800,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1041,
    eventId: 241,
    title: 'Поцелуй. Конармия',
    summary: 'Драмы. Театр на Таганке, ул. Земляной Вал, 76/21. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/pocelui-konarmiya-41.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/60/89/60897716657d68295832342958972508_4625573.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/poceluy-konarmiya/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-taganke/poceluy-konarmiya/',
    venueName: 'Театр на Таганке',
    venueAddress: 'ул. Земляной Вал, 76/21',
    startsAt: '2026-10-09T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 2.4,
    sessionCount: 1
  },
  {
    sessionId: 1042,
    eventId: 242,
    title: 'Вахтангов. Путь к Турандот',
    summary: 'Пешеходные экскурсии. Театр Вахтангова (экскурсии), ул. Арбат, 26. В афише один сеанс.',
    category: 'EXCURSION',
    photo: 'assets/events/vahtangov-put-k-turandot-42.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/show/4338298/1.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/vakhtangov-put-k-turandot/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/vakhtangov-put-k-turandot/',
    venueName: 'Театр Вахтангова (экскурсии)',
    venueAddress: 'ул. Арбат, 26',
    startsAt: '2026-10-10T12:30:00+03:00',
    priceRub: 1400,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1043,
    eventId: 243,
    title: 'Аничков мост',
    summary: 'Детям, драмы. Театр на Малой Ордынке, ул. Малая Ордынка, 31. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/anichkov-most-43.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/22/aa/22aae1c72ec3fbcc4d004cfadbb70808.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-maloy-ordynke/anichkov-most-spektakl/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-maloy-ordynke/anichkov-most-spektakl/',
    venueName: 'Театр на Малой Ордынке',
    venueAddress: 'ул. Малая Ордынка, 31',
    startsAt: '2026-10-10T14:00:00+03:00',
    priceRub: 2000,
    distanceKm: 2.1,
    sessionCount: 1
  },
  {
    sessionId: 1044,
    eventId: 244,
    title: 'Серебряный век. Цех поэтов. Гумилев, Ахматова....',
    summary: 'Творческие вечера. Музыкальная квартира на Тверской, ул. Тверская, 12с7. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/serebryanyi-vek-ceh-poetov-gumilev-ahm-44.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/55/90/5590157b6c5ed585167172b9caaee59d.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/muzykalnaya-kvartira-na-tverskoy/serebryanyy-vek-cekh-poetov-gumilev-akhmatova/',
    ticketUrl: 'https://www.ticketland.ru/teatry/muzykalnaya-kvartira-na-tverskoy/serebryanyy-vek-cekh-poetov-gumilev-akhmatova/',
    venueName: 'Музыкальная квартира на Тверской',
    venueAddress: 'ул. Тверская, 12с7',
    startsAt: '2026-10-10T19:00:00+03:00',
    priceRub: 700,
    distanceKm: 1.5,
    sessionCount: 1
  },
  {
    sessionId: 1045,
    eventId: 245,
    title: 'Музыкальные вечера на Арбате. Композиторы-романтики: Шуберт, Шуман, Брамс',
    summary: 'Концерты, инструментальная музыка. Музей Скрябина, Большой Николопесковский пер., 11. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/muzykalnye-vechera-na-arbate-kompozito-45.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/fc/45/fc45d21588bc8f04fef4422fb1c53c1c.jpg',
    eventUrl: 'https://www.ticketland.ru/muzei/muzey-anskryabina/muzykalnye-vechera-na-arbate-kompozitory-romantiki-shubertshumanbrams/',
    ticketUrl: 'https://www.ticketland.ru/muzei/muzey-anskryabina/muzykalnye-vechera-na-arbate-kompozitory-romantiki-shubertshumanbrams/',
    venueName: 'Музей Скрябина',
    venueAddress: 'Большой Николопесковский пер., 11',
    startsAt: '2026-10-10T19:00:00+03:00',
    priceRub: 800,
    distanceKm: 2,
    sessionCount: 1
  },
  {
    sessionId: 1046,
    eventId: 246,
    title: 'Главная роль',
    summary: 'Драмы. Сцена «Студия» театра Вахтангова, Большой Николопесковский пер., 11. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/glavnaya-rol-46.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/75/a1/75a1ac5f5620b8f455925b725f0d9d5c.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/scena-studiya-teatra-vakhtangova/glavnaya-rol/',
    ticketUrl: 'https://www.ticketland.ru/teatry/scena-studiya-teatra-vakhtangova/glavnaya-rol/',
    venueName: 'Сцена «Студия» театра Вахтангова',
    venueAddress: 'Большой Николопесковский пер., 11',
    startsAt: '2026-10-10T19:30:00+03:00',
    priceRub: 1500,
    distanceKm: 2,
    sessionCount: 1
  },
  {
    sessionId: 1047,
    eventId: 247,
    title: 'Cказка о попе и работнике его Балде',
    summary: 'Спектакли, детям от 7 до 11 лет. Новая сцена и Арт-кафе театра Вахтангова, ул. Арбат, 24. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/ckazka-o-pope-i-rabotnike-ego-balde-47.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/92/8e/928e7945e6e036f809518014c8d0e899_3879635.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/novaya-scena-i-art-kafe-teatra-vakhtangova/spektakl-ckazka-o-pope-i-rabotnike-ego-balde/',
    ticketUrl: 'https://www.ticketland.ru/teatry/novaya-scena-i-art-kafe-teatra-vakhtangova/spektakl-ckazka-o-pope-i-rabotnike-ego-balde/',
    venueName: 'Новая сцена и Арт-кафе театра Вахтангова',
    venueAddress: 'ул. Арбат, 24',
    startsAt: '2026-10-11T13:00:00+03:00',
    priceRub: 2200,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1048,
    eventId: 248,
    title: 'Алые паруса',
    summary: 'Детям от 12 до 15 лет. Театр на Малой Ордынке, ул. Малая Ордынка, 31. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/alye-parusa-48.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/b6/87/b687ddfafb06026d03a4e0857368b07a.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-maloy-ordynke/parusa-alye/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-maloy-ordynke/parusa-alye/',
    venueName: 'Театр на Малой Ордынке',
    venueAddress: 'ул. Малая Ордынка, 31',
    startsAt: '2026-10-11T14:00:00+03:00',
    priceRub: 2000,
    distanceKm: 2.1,
    sessionCount: 1
  },
  {
    sessionId: 1049,
    eventId: 249,
    title: 'Манюня',
    summary: 'Детям от 12 до 15 лет. РАМТ, Театральная пл., 2. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/manyunya-49.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/show/3973519/1.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/ramt/manyunya-spektakl/',
    ticketUrl: 'https://www.ticketland.ru/teatry/ramt/manyunya-spektakl/',
    venueName: 'РАМТ',
    venueAddress: 'Театральная пл., 2',
    startsAt: '2026-10-11T19:00:00+03:00',
    priceRub: 1500,
    distanceKm: 0.8,
    sessionCount: 1
  },
  {
    sessionId: 1050,
    eventId: 250,
    title: 'Хорошие фото',
    summary: 'Драмы. Театр на Малой Ордынке, ул. Малая Ордынка, 31. В афише один сеанс.',
    category: 'THEATRE',
    photo: 'assets/events/horoshie-foto-50.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/98/a1/98a10b8df98764cc531d873837eb5962.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-na-maloy-ordynke/khoroshie-foto/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-na-maloy-ordynke/khoroshie-foto/',
    venueName: 'Театр на Малой Ордынке',
    venueAddress: 'ул. Малая Ордынка, 31',
    startsAt: '2026-10-13T19:00:00+03:00',
    priceRub: 1500,
    distanceKm: 2.1,
    sessionCount: 1
  },
  {
    sessionId: 1051,
    eventId: 251,
    title: 'Музыкальные вечера на Арбате. Игорь Полтавцев (фортепиано). Шопен, Шуман, Лист, Брамс',
    summary: 'Концерты, инструментальная музыка. Музей Скрябина, Большой Николопесковский пер., 11. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/muzykalnye-vechera-na-arbate-igor-polt-51.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/ea/58/ea5827d8370a546ad03579c8d16bf258.jpg',
    eventUrl: 'https://www.ticketland.ru/muzei/muzey-anskryabina/muzykalnye-vechera-na-arbate-igor-poltavcev-fortepiano-shopen-shuman-list-brams/',
    ticketUrl: 'https://www.ticketland.ru/muzei/muzey-anskryabina/muzykalnye-vechera-na-arbate-igor-poltavcev-fortepiano-shopen-shuman-list-brams/',
    venueName: 'Музей Скрябина',
    venueAddress: 'Большой Николопесковский пер., 11',
    startsAt: '2026-10-13T19:00:00+03:00',
    priceRub: 600,
    distanceKm: 2,
    sessionCount: 1
  },
  {
    sessionId: 1052,
    eventId: 252,
    title: 'Балет «Спящая красавица»',
    summary: 'Спектакли, балет. Москонцерт Холл, Каланчёвская ул., 33с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/balet-spyaschaya-krasavica-52.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/0a/58/0a586d86577e5acb836bc854b1c6804b.png',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/spyaschaya-krasavica/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/spyaschaya-krasavica/',
    venueName: 'Москонцерт Холл',
    venueAddress: 'Каланчёвская ул., 33с1',
    startsAt: '2026-10-17T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 3,
    sessionCount: 1
  },
  {
    sessionId: 1053,
    eventId: 253,
    title: 'Музыкальные вечера на Арбате.Александр Гиндин (фортепиано). Шуберт, Лист',
    summary: 'Концерты, инструментальная музыка. Музей Скрябина, Большой Николопесковский пер., 11. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/muzykalnye-vechera-na-arbate-aleksandr-53.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/b7/73/b7734df8a4259fa44d8d739e082388a4.jpg',
    eventUrl: 'https://www.ticketland.ru/muzei/muzey-anskryabina/muzykalnye-vechera-na-arbatealeksandr-gindin-fortepiano-shubert-list/',
    ticketUrl: 'https://www.ticketland.ru/muzei/muzey-anskryabina/muzykalnye-vechera-na-arbatealeksandr-gindin-fortepiano-shubert-list/',
    venueName: 'Музей Скрябина',
    venueAddress: 'Большой Николопесковский пер., 11',
    startsAt: '2026-10-21T19:00:00+03:00',
    priceRub: 600,
    distanceKm: 2,
    sessionCount: 1
  },
  {
    sessionId: 1054,
    eventId: 254,
    title: 'Экскурсия по театру. Прошлое и настоящее',
    summary: 'Пешеходные экскурсии. Театр имени Евгения Вахтангова, ул. Арбат, 26. В афише один сеанс.',
    category: 'EXCURSION',
    photo: 'assets/events/ekskursiya-po-teatru-proshloe-i-nastoy-54.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/c9/70/c970a263863cae2a15fdce02db9cd0b1_1856104.jpg',
    eventUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/ekskyrsiya-po-teatry-proshloe-i-nastoyashhee/',
    ticketUrl: 'https://www.ticketland.ru/teatry/teatr-imeni-evgeniya-vakhtangova/ekskyrsiya-po-teatry-proshloe-i-nastoyashhee/',
    venueName: 'Театр имени Евгения Вахтангова',
    venueAddress: 'ул. Арбат, 26',
    startsAt: '2026-10-24T12:00:00+03:00',
    priceRub: 1200,
    distanceKm: 1.8,
    sessionCount: 1
  },
  {
    sessionId: 1055,
    eventId: 255,
    title: 'Дон Кихот',
    summary: 'Детям, балет. Москонцерт Холл, Каланчёвская ул., 33с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/don-kihot-55.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/6d/8e/6d8e4631448cd7190979ee0ab4610e5c.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/don-kikhot/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/moskoncert-kholl/don-kikhot/',
    venueName: 'Москонцерт Холл',
    venueAddress: 'Каланчёвская ул., 33с1',
    startsAt: '2026-10-25T19:00:00+03:00',
    priceRub: 800,
    distanceKm: 3,
    sessionCount: 1
  },
  {
    sessionId: 1056,
    eventId: 256,
    title: 'Щелкунчик (Театр классического балета имени Касаткиной и Василева)',
    summary: 'Спектакли, концерты. Центр оперного пения Галины Вишневской, ул. Остоженка, 25с1. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/schelkunchik-teatr-klassicheskogo-bale-56.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/2e/cc/2ecc48cc30be3fa87b869798640e4bf7.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/centr-opernogo-peniya-galiny-vishnevskoy/schelkunchik-center-galiny-vishnevskoy/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/centr-opernogo-peniya-galiny-vishnevskoy/schelkunchik-center-galiny-vishnevskoy/',
    venueName: 'Центр оперного пения Галины Вишневской',
    venueAddress: 'ул. Остоженка, 25с1',
    startsAt: '2026-11-03T19:00:00+03:00',
    priceRub: 1000,
    distanceKm: 2.3,
    sessionCount: 1
  },
  {
    sessionId: 1057,
    eventId: 257,
    title: 'Анжелика Варум и Леонид Агутин',
    summary: 'Поп-музыка. Live Арена, Красногорск, Международная ул., 16. В афише один сеанс.',
    category: 'CONCERT',
    photo: 'assets/events/anzhelika-varum-i-leonid-agutin-57.jpg',
    posterUrl: 'https://media.ticketland.ru/images/250x250/00/d1/00d1d3d5e30229fa3e91ea5b318b386a.jpg',
    eventUrl: 'https://www.ticketland.ru/koncertnye-zaly/live-arena/anzhelika-varum-i-leonid-agutin/',
    ticketUrl: 'https://www.ticketland.ru/koncertnye-zaly/live-arena/anzhelika-varum-i-leonid-agutin/',
    venueName: 'Live Арена',
    venueAddress: 'Красногорск, Международная ул., 16',
    startsAt: '2026-12-11T20:00:00+03:00',
    priceRub: 3000,
    distanceKm: 19.4,
    sessionCount: 1
  }
];

if (typeof module !== 'undefined') { module.exports = MOCK_EVENTS; }
